# Site settings
title: Keisan Gittens Portfolio
description: Keisan Gittens Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Keisan Gittens
user_description: <div class="about-bl">Thanks for checking me out! I just graduated from the City and Regional Planning program at the <a class="bottomlink" class="paralinks" href="https://www.design.upenn.edu/city-regional-planning/graduate/work" target="blank">Stuart Weitzman School of Design</a> at Penn. You're probably wondering who I am and what I'm like. I am a designer and data nerd, who is passionate about climate change and sustainability. My goals are to use design, information technology and policy to achieve sustainability targets via the planning process.   <br/><br/> </div><div id="lastp" class="about-bl">When I'm not trying aggressively trying to learn something new, you can find me spending time at wildlife conservancies, hiking trails, working up a sweat at the gym, shopping at farmers markets, biking or geeking out over a new Netflix documentary. I'm a big scrabble fan, (former competitive player), and always try to catch local concerts. I'm an avid learner and love a great mind bending problem. I'm very ambitious so naturally I am constantly improving myself, learning from mistakes and working towards being a better version of myself. 
Ps: I'm working on redesigning this site!
  </div>
user_title: Urban Planner <br> Designer
email: keisangittens@gmail.com
twitter_username: whatisyourllama
github_username:  Nasiek
gplus_username:  KeisanGittens

# Google-analytics
google-analytics:
  id: ""
## plugins
plugins:
  - "jekyll-github-metadata"
## baseurl
exclude: ['package.json', 'src' , 'node_modules']
