# Site settings
title: Keisan Gittens Portfolio
description: Keisan Gittens Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Keisan Gittens
user_description: <p class="about-bl">Currently a web developer intern at <a class="bottomlink" class="paralinks" href="https://milkcrate.tech/" target="blank">Milkcrate LLC</a> focusing on data visualization using the D3.js Library. My interests are object oriented programming, web development, Python scripting, DevOps and QA testing, as well as statistical programming, urban planning, and data science. For fun, I like outdoor recreation such as hiking, biking and trail running, playing scrabble (former competitive player), and going to local concerts. I value making esoteric topics accessible to broader audiences, learning from others' and using my education, skills and experiences to solve complex problems. I am always improving myself, learning from mistakes and working towards being a better programmer and analyst.
  </p><p class='about-bl'> I learnt HTML, CSS, JavaScript and Ruby on Rails in just a couple months. Now with my strong foundation, I'm learning Angular and React for web development and moving deeper into  Python 3 for data analysis and web scraping as well as desktop apps.</p>
user_title: Web Developer <br> Data Analyst
email: keisangittens@gmail.com
twitter_username: whatisyourllama
github_username:  Nasiek
gplus_username:  KeisanGittens

# Google-analytics
google-analytics:
  id: ""
## plugins
plugins:
  - "jekyll-github-metadata"
## baseurl
exclude: ['package.json', 'src' , 'node_modules']
