# Site settings
title: Keisan Gittens Portfolio
description: Keisan Gittens Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Keisan Gittens
user_description: <div class="about-bl">Currently a web developer intern at <a class="bottomlink" class="paralinks" href="https://milkcrate.tech/" target="blank">Milkcrate LLC</a> focusing on data visualization using the D3.js Library. My interests are object oriented programming, web development, Python scripting, DevOps and QA testing, as well as statistical programming, urban planning, and data science. <br/><br/> I learnt HTML, CSS, JavaScript and Ruby on Rails in just a couple months. Now with my strong foundation, I'm learning Angular and React for web development and moving deeper into  Python 3 for data analysis and web scraping as well as desktop apps.</div><div id="lastp" class="about-bl">For fun, I like outdoor recreation such as hiking, biking and trail running, playing scrabble (former competitive player), and going to local concerts. I'm really into accessibility, I'm an avid learner and love a great mind bending problem. I'm really ambitious so naturally I am always improving myself, learning from mistakes and working towards being a better programmer and analyst.
  </div>
user_title: Web Developer <br> Data Analyst
email: keisangittens@gmail.com
twitter_username: whatisyourllama
github_username:  Nasiek
gplus_username:  KeisanGittens

# Google-analytics
google-analytics:
  id: ""
## plugins
plugins:
  - "jekyll-github-metadata"
## baseurl
exclude: ['package.json', 'src' , 'node_modules']
