# Site settings
title: Keisan Gittens Portfolio
description: Keisan Gittens Portfolio
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Keisan Gittens
user_description: <div class="about-bl"> I'm a graduate student in City and Regional Planning at the University of Pennsylvania's<a class="bottomlink" class="paralinks" href="https://www.design.upenn.edu/city-regional-planning/graduate/work" target="blank">Stuart Weitzman School of Design.</a>  I'm focusing on community and economic development, however I am extremely interested in sustainability, web development and human computer interaction, geospatial data analytics, international development, food systems, and urban design. As you can see I have many interests, and am cultivating an interdisplinary skillset to address them respectively.  <br/><br/> </div><div id="lastp" class="about-bl">For fun, I like hiking, biking and trail running, playing scrabble (former competitive player), and going to local concerts. I'm an avid learner and love a great mind bending problem. I'm really ambitious so naturally I am always improving myself, learning from mistakes and working towards being a better version of myself.
  </div>
user_title: Web Developer <br> Data Analyst
email: keisangittens@gmail.com
twitter_username: whatisyourllama
github_username:  Nasiek
gplus_username:  KeisanGittens

# Google-analytics
google-analytics:
  id: ""
## plugins
plugins:
  - "jekyll-github-metadata"
## baseurl
exclude: ['package.json', 'src' , 'node_modules']
